// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AdminController from "./admin_controller"
application.register("admin", AdminController)

import CookiesController from "./cookies_controller"
application.register("cookies", CookiesController)

import CryptoController from "./crypto_controller"
application.register("crypto", CryptoController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NftsController from "./nfts_controller"
application.register("nfts", NftsController)

import OrdersController from "./orders_controller"
application.register("orders", OrdersController)

import PhotographyController from "./photography_controller"
application.register("photography", PhotographyController)

import PriceController from "./price_controller"
application.register("price", PriceController)

import TopController from "./top_controller"
application.register("top", TopController)

import WorksController from "./works_controller"
application.register("works", WorksController)
