// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PhotographyController from "./photography_controller"
application.register("photography", PhotographyController)

import PriceController from "./price_controller"
application.register("price", PriceController)

import WorksController from "./works_controller"
application.register("works", WorksController)
